### ISSUE TITLE
Features and Pump Stats

### ISSUE THREAD

**Issue by btreinders** [brianmtreese/nodejs-pool-controller-polyglotv2#3]
Any chance you can add pump features, GPMs, RPMs and watts to the ISY nodes server?  I could decommission my Arduino sensor if I could use those as nodes.  Well, features as nodes and the others just into ISY variables.  Intellibrite colors and Intellichlor control would be awesome too! Thanks!

**Comment by brianmtreese** [comment]
Sure, I don't think this will be all that hard! I'll add them as soon as I can, thanks!

**Comment by btreinders** [comment]
Awesome!  I am also getting an exception about once a day.  I have to restart the node server when it happens.  I posted it in the forums.  Here is what I see in the logs.  Thanks!

2019-01-29 19:06:57,435 [Controller] [ERROR] Exception in thread Controller: Traceback (most recent call last): File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connection.py", line 159, in _new_conn (self._dns_host, self.port), self.timeout, **extra_kw) File "/home/pi/.local/lib/python3.5/site-packages/urllib3/util/connection.py", line 80, in create_connection raise err File "/home/pi/.local/lib/python3.5/site-packages/urllib3/util/connection.py", line 70, in create_connection sock.connect(sa) ConnectionRefusedError: [Errno 111] Connection refused During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 600, in urlopen chunked=chunked) File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 354, in _make_request conn.request(method, url, **httplib_request_kw) File "/usr/lib/python3.5/http/client.py", line 1107, in request self._send_request(method, url, body, headers) File "/usr/lib/python3.5/http/client.py", line 1152, in _send_request self.endheaders(body) File "/usr/lib/python3.5/http/client.py", line 1103, in endheaders self._send_output(message_body) File "/usr/lib/python3.5/http/client.py", line 934, in _send_output self.send(msg) File "/usr/lib/python3.5/http/client.py", line 877, in send self.connect() File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connection.py", line 181, in connect conn = self._new_conn() File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connection.py", line 168, in _new_conn self, "Failed to establish a new connection: %s" % e) urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x75c19c70>: Failed to establish a new connection: [Errno 111] Connection refused During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/home/pi/.local/lib/python3.5/site-packages/requests/adapters.py", line 449, in send timeout=timeout File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 638, in urlopen _stacktrace=sys.exc_info()[2]) File "/home/pi/.local/lib/python3.5/site-packages/urllib3/util/retry.py", line 398, in increment raise MaxRetryError(_pool, url, error or ResponseError(cause)) urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='192.168.1.32', port=3000): Max retries exceeded with url: /circuit/5 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x75c19c70>: Failed to establish a new connection: [Errno 111] Connection refused',)) During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner self.run() File "/usr/lib/python3.5/threading.py", line 862, in run self._target(*self._args, **self._kwargs) File "/home/pi/.local/lib/python3.5/site-packages/polyinterface/polyinterface.py", line 769, in _parseInput self.shortPoll() File "./pool-poly.py", line 81, in shortPoll self.nodes[node].update() File "./pool-poly.py", line 194, in update self.get_status() File "./pool-poly.py", line 201, in get_status circuitData = requests.get(url='{0}/circuit/{1}'.format(self.apiBaseUrl, self.number)) File "/home/pi/.local/lib/python3.5/site-packages/requests/api.py", line 75, in get return request('get', url, params=params, **kwargs) File "/home/pi/.local/lib/python3.5/site-packages/requests/api.py", line 60, in request return session.request(method=method, url=url, **kwargs) File "/home/pi/.local/lib/python3.5/site-packages/requests/sessions.py", line 533, in request resp = self.send(prep, **send_kwargs) File "/home/pi/.local/lib/python3.5/site-packages/requests/sessions.py", line 646, in send r = adapter.send(request, **kwargs) File "/home/pi/.local/lib/python3.5/site-packages/requests/adapters.py", line 516, in send raise ConnectionError(e, request=request) requests.exceptions.ConnectionError: HTTPConnectionPool(host='192.168.1.32', port=3000): Max retries exceeded with url: /circuit/5 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x75c19c70>: Failed to establish a new connection: [Errno 111] Connection refused',))



________________________________

**Comment by brianmtreese** [comment]
This is strange, it looks like it's a communication error with "circuit 5". Do you have to restart the nodejs pool controller app too?

**Comment by btreinders** [comment]
Well, I have always started both but this time I just restarted the nodejs pool controller and it never reconnected until I restarted the node server too.  Next time I'll try just the node server first.

Thanks!


________________________________

**Comment by brianmtreese** [comment]
When this happens are there any errors occurring in the nodejs pool
controller app or is it just the polyglot node server?

**Comment by btreinders** [comment]
Sorry, I can't scroll up enough to see.  I'll pay attention next time.

________________________________

**Comment by btreinders** [comment]
Of course it hasn't crashed again today or yesterday.  Once it does (if) I'll let you know.
Thanks,
Brent


________________________________

**Comment by btreinders** [comment]
Had another crash, no errors from the poolController, restarted just the node server and it worked.

What I saw from the log for the node server.

Driver controller - CLITEMP: 50, uom: 17 2019-02-09 15:31:32,825 [Controller] [INFO ] Updating Driver controller - CLITEMP: 51, uom: 17 2019-02-09 15:40:53,567 [Controller] [INFO ] Updating Driver controller - CLITEMP: 50, uom: 17 2019-02-09 15:55:24,931 [Controller] [ERROR] Exception in thread Controller: Traceback (most recent call last): File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 600, in urlopen chunked=chunked) File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 384, in _make_request six.raise_from(e, None) File "<string>", line 2, in raise_from File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 380, in _make_request httplib_response = conn.getresponse() File "/usr/lib/python3.5/http/client.py", line 1198, in getresponse response.begin() File "/usr/lib/python3.5/http/client.py", line 297, in begin version, status, reason = self._read_status() File "/usr/lib/python3.5/http/client.py", line 258, in _read_status line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1") File "/usr/lib/python3.5/socket.py", line 576, in readinto return self._sock.recv_into(b) ConnectionResetError: [Errno 104] Connection reset by peer During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/home/pi/.local/lib/python3.5/site-packages/requests/adapters.py", line 449, in send timeout=timeout File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 638, in urlopen _stacktrace=sys.exc_info()[2]) File "/home/pi/.local/lib/python3.5/site-packages/urllib3/util/retry.py", line 367, in increment raise six.reraise(type(error), error, _stacktrace) File "/home/pi/.local/lib/python3.5/site-packages/urllib3/packages/six.py", line 685, in reraise raise value.with_traceback(tb) File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 600, in urlopen chunked=chunked) File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 384, in _make_request six.raise_from(e, None) File "<string>", line 2, in raise_from File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 380, in _make_request httplib_response = conn.getresponse() File "/usr/lib/python3.5/http/client.py", line 1198, in getresponse response.begin() File "/usr/lib/python3.5/http/client.py", line 297, in begin version, status, reason = self._read_status() File "/usr/lib/python3.5/http/client.py", line 258, in _read_status line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1") File "/usr/lib/python3.5/socket.py", line 576, in readinto return self._sock.recv_into(b) urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')) During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner self.run() File "/usr/lib/python3.5/threading.py", line 862, in run self._target(*self._args, **self._kwargs) File "/home/pi/.local/lib/python3.5/site-packages/polyinterface/polyinterface.py", line 769, in _parseInput self.shortPoll() File "./pool-poly.py", line 81, in shortPoll self.nodes[node].update() File "./pool-poly.py", line 194, in update self.get_status() File "./pool-poly.py", line 201, in get_status circuitData = requests.get(url='{0}/circuit/{1}'.format(self.apiBaseUrl, self.number)) File "/home/pi/.local/lib/python3.5/site-packages/requests/api.py", line 75, in get return request('get', url, params=params, **kwargs) File "/home/pi/.local/lib/python3.5/site-packages/requests/api.py", line 60, in request return session.request(method=method, url=url, **kwargs) File "/home/pi/.local/lib/python3.5/site-packages/requests/sessions.py", line 533, in request resp = self.send(prep, **send_kwargs) File "/home/pi/.local/lib/python3.5/site-packages/requests/sessions.py", line 646, in send r = adapter.send(request, **kwargs) File "/home/pi/.local/lib/python3.5/site-packages/requests/adapters.py", line 498, in send raise ConnectionError(err, request=request) requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

________________________________
