### ISSUE TITLE
Is this app still up to date? api_url example refers to port 3000

### ISSUE THREAD

**Issue by psmith3** [brianmtreese/nodejs-pool-controller-polyglotv2#5]
Shouldn't the api_url be pointing to port 4200? All I see is the following connective errors in the log.I am running Polyglot in a docker container on the same host and Polyglot uses port 3000. I am also trying to pull the Salt Level from my virtual controller for an Aquarite. Not sure it will read the salt level though. 

`2021-06-29 23:11:26,780 Controller polyinterface      ERROR    polyinterface:write: HTTPConnectionPool(host='172.30.17.172', port=4200): Max retries exceeded with url: /all (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f19537ddac0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2021-06-29 23:11:26,781 Controller polyinterface      ERROR    polyinterface:write: During handling of the above exception, another exception occurred:
2021-06-29 23:11:26,781 Controller polyinterface      ERROR    polyinterface:write: Traceback (most recent call last):
2021-06-29 23:11:26,781 Controller polyinterface      ERROR    polyinterface:write: File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
2021-06-29 23:11:26,782 Controller polyinterface      ERROR    polyinterface:write: self.run()
2021-06-29 23:11:26,783 Controller polyinterface      ERROR    polyinterface:write: File "/usr/lib/python3.8/threading.py", line 870, in run
2021-06-29 23:11:26,784 Controller polyinterface      ERROR    polyinterface:write: self._target(*self._args, **self._kwargs)
2021-06-29 23:11:26,784 Controller polyinterface      ERROR    polyinterface:write: File "/root/.local/lib/python3.8/site-packages/polyinterface/polyinterface.py", line 852, in _parseInput
2021-06-29 23:11:26,786 Controller polyinterface      ERROR    polyinterface:write: self.shortPoll()
2021-06-29 23:11:26,786 Controller polyinterface      ERROR    polyinterface:write: File "./pool-poly.py", line 81, in shortPoll
2021-06-29 23:11:26,787 Controller polyinterface      ERROR    polyinterface:write: self.nodes[node].update()
2021-06-29 23:11:26,787 Controller polyinterface      ERROR    polyinterface:write: File "./pool-poly.py", line 121, in update
2021-06-29 23:11:26,788 Controller polyinterface      ERROR    polyinterface:write: controllerData = requests.get(url='{}/all'.format(self.apiBaseUrl))
2021-06-29 23:11:26,788 Controller polyinterface      ERROR    polyinterface:write: File "/root/.local/lib/python3.8/site-packages/requests/api.py", line 76, in get
2021-06-29 23:11:26,789 Controller polyinterface      ERROR    polyinterface:write: return request('get', url, params=params, **kwargs)
2021-06-29 23:11:26,790 Controller polyinterface      ERROR    polyinterface:write: File "/root/.local/lib/python3.8/site-packages/requests/api.py", line 61, in request
2021-06-29 23:11:26,790 Controller polyinterface      ERROR    polyinterface:write: return session.request(method=method, url=url, **kwargs)
2021-06-29 23:11:26,790 Controller polyinterface      ERROR    polyinterface:write: File "/root/.local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
2021-06-29 23:11:26,804 Controller polyinterface      ERROR    polyinterface:write: resp = self.send(prep, **send_kwargs)
2021-06-29 23:11:26,804 Controller polyinterface      ERROR    polyinterface:write: File "/root/.local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
2021-06-29 23:11:26,805 Controller polyinterface      ERROR    polyinterface:write: r = adapter.send(request, **kwargs)
2021-06-29 23:11:26,805 Controller polyinterface      ERROR    polyinterface:write: File "/root/.local/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
2021-06-29 23:11:26,806 Controller polyinterface      ERROR    polyinterface:write: raise ConnectionError(e, request=request)
2021-06-29 23:11:26,807 Controller polyinterface      ERROR    polyinterface:write: requests.exceptions
2021-06-29 23:11:26,807 Controller polyinterface      ERROR    polyinterface:write: .
2021-06-29 23:11:26,807 Controller polyinterface      ERROR    polyinterface:write: ConnectionError
2021-06-29 23:11:26,807 Controller polyinterface      ERROR    polyinterface:write: :
2021-06-29 23:11:26,808 Controller polyinterface      ERROR    polyinterface:write: HTTPConnectionPool(host='172.30.17.172', port=4200): Max retries exceeded with url: /all (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f19537ddac0>: Failed to establish a new connection: [Errno 111] Connection refused'))`

**Comment by brianmtreese** [comment]
Unfortunately I'm not maintaining this project anymore. I've switched to home assistant and have a different set up now. Sorry.
